"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var auto_1 = require("./auto");
var camioneta_1 = require("./camioneta");
var moto_1 = require("./moto");
var registroAutomotor_1 = require("./registroAutomotor");
var registro = new registroAutomotor_1.RegistroAutomotor();
var auto = new auto_1.Auto("Chevrolet", "Corsa", 2008, 5);
var camioneta = new camioneta_1.Camioneta("Ford", "Maverick", 2024, 1500);
var moto = new moto_1.Moto("Yamaha", "SR1000", 2022, 1150);
registro.agregarVehiculo(auto);
registro.agregarVehiculo(camioneta);
registro.agregarVehiculo(moto);
console.log(JSON.stringify(registro.listarVehiculos()));
var auto1 = new auto_1.Auto("Fiat", "Spazio CL", 1987, 3);
registro.modificarVehiculo(0, auto1);
console.log(JSON.stringify(registro.listarVehiculos()));
registro.eliminarVehiculo(1);
console.log(JSON.stringify(registro.listarVehiculos()));
